test_cases: add httpd dependencies
Signed-off-by: Joey Pabalinas <joeypabalinas@gmail.com>

diff --git a/test_cases/httpd/bootstrap_nacl b/test_cases/httpd/bootstrap_nacl
--- a/test_cases/httpd/bootstrap_nacl
+++ b/test_cases/httpd/bootstrap_nacl
@@ -12,15 +12,16 @@ fi
 export CC=x86_64-nacl-gcc
 export CXX=x86_64-nacl-g++
 export LD=x86_64-nacl-ld
-export CFLAGS='-DPTHREAD_MUTEX_RECURSIVE=1 -g -fno-pie'
-export CXXFLAGS='-DPTHREAD_MUTEX_RECURSIVE=1 -g -fno-pie'
-export LDFLAGS='-g -fno-pie'
+export CFLAGS='-DPTHREAD_MUTEX_RECURSIVE=1 -g -fPIC'
+export CXXFLAGS='-DPTHREAD_MUTEX_RECURSIVE=1 -g -fPIC'
+export LDFLAGS='-g -fPIC'
+export PREFIX="${PREFIX:-$HOME/lind_project/lind/repy/repy}"
 export PATH="/usr/bin:/usr/sbin:/bin:/sbin:$PATH"
 
 mkdir -pv -- apr
 make distclean || true
 rm -fv -- ./configure
-for d in srclib/apr-util srclib/apr; do
+for d in srclib/apr{,-util}; do
 	(cd "$d" \
 		&& (make distclean || true) \
 		&& rm -fv -- ./configure \
@@ -31,7 +32,12 @@ cp -fv -- srclib/apr-util/include/{apr_{hooks,optional_hooks,buckets,uri,optiona
 ./buildconf
 ./configure \
 	--with-included-apr \
-	--with-expat="$PREFIX/lib" \
+	--with-libxml2="$PREFIX/lib" \
+	--with-brotli="$PREFIX" \
+	--with-pcre="$PREFIX" \
+	--with-z="$PREFIX" \
+	--enable-pie \
+	--enable-modules=none \
 	--host=x86_64-nacl \
 	--prefix="${PREFIX:-$HOME/lind_project/lind/repy/repy}" \
 	"$@" \
@@ -46,4 +52,10 @@ cp -fv -- srclib/apr-util/include/{apr_{hooks,optional_hooks,buckets,uri,optiona
 
 patch -Np1 <./httpd.h.patch || true
 
-make
+# fix multiple definition errors
+if ! make; then
+	cp -fv -- server/exports.c{.patched,}
+	patch -Np1 <./mutex.patch || true
+	make
+fi
+make install
